runtime: go111

main: dashboard/app

inbound_services:
- mail
- mail_bounce

handlers:
- url: /favicon.ico
  static_files: dashboard/app/static/favicon.ico
  upload: static/favicon.ico
  secure: always
- url: /robots.txt
  static_files: dashboard/app/static/robots.txt
  upload: static/robots.txt
  secure: always
- url: /static
  static_dir: dashboard/app/static
  secure: always
- url: /(admin|email_poll)
  script: auto
  login: admin
  secure: always
- url: /_ah/(mail/.+|bounce)
  script: auto
  login: admin
- url: /(|api|bug|text|x/.+|.*)
  script: auto
  secure: always
